//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


class kuzunetPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="SWIGRegisterExceptionCallbacks_kuzunet")]
    public static extern void SWIGRegisterExceptionCallbacks_kuzunet(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_kuzunet")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_kuzunet(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_kuzunet(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_kuzunet(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="SWIGRegisterStringCallback_kuzunet")]
    public static extern void SWIGRegisterStringCallback_kuzunet(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_kuzunet(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  public class SWIGStringWithLengthHelper {

    [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="SWIG_csharp_string_to_c")]
    private static extern global::System.IntPtr SWIG_csharp_string_to_c0(int size, int len, [global::System.Runtime.InteropServices.In,global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr, SizeParamIndex=0)] string str);

    [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="SWIG_csharp_string_size")]
    private static extern int SWIG_csharp_string_size(global::System.IntPtr str);

    [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="SWIG_csharp_string_str")]
    private static extern global::System.IntPtr SWIG_csharp_string_str(global::System.IntPtr str);

    public static global::System.IntPtr SWIG_csharp_string_to_c(string str) {
      if (str == null)
        return global::System.IntPtr.Zero;
      global::System.Text.Encoding utf8 = global::System.Text.Encoding.UTF8;
      return SWIG_csharp_string_to_c0(utf8.GetByteCount(str), str.Length, str);
    }

    public static string SWIG_c_to_csharp_string(global::System.IntPtr str) {
      int size = SWIG_csharp_string_size(str);
      if (size > 0) {
        global::System.IntPtr s = SWIG_csharp_string_str(str);
        byte[] b = new byte[size];
        global::System.Runtime.InteropServices.Marshal.Copy(s, b, 0, size);
        global::System.Text.Encoding utf8 = global::System.Text.Encoding.UTF8;
        return utf8.GetString(b);
      }
      return null;
    }
  }


  static kuzunetPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_has_internal")]
  public static extern int kuzu_value_has_internal(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_system_config_buffer_pool_size_set")]
  public static extern void kuzu_system_config_buffer_pool_size_set(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_system_config_buffer_pool_size_get")]
  public static extern ulong kuzu_system_config_buffer_pool_size_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_system_config_max_num_threads_set")]
  public static extern void kuzu_system_config_max_num_threads_set(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_system_config_max_num_threads_get")]
  public static extern ulong kuzu_system_config_max_num_threads_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_system_config_enable_compression_set")]
  public static extern void kuzu_system_config_enable_compression_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_system_config_enable_compression_get")]
  public static extern bool kuzu_system_config_enable_compression_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_system_config_read_only_set")]
  public static extern void kuzu_system_config_read_only_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_system_config_read_only_get")]
  public static extern bool kuzu_system_config_read_only_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_system_config_max_db_size_set")]
  public static extern void kuzu_system_config_max_db_size_set(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_system_config_max_db_size_get")]
  public static extern ulong kuzu_system_config_max_db_size_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_system_config_auto_checkpoint_set")]
  public static extern void kuzu_system_config_auto_checkpoint_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_system_config_auto_checkpoint_get")]
  public static extern bool kuzu_system_config_auto_checkpoint_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_system_config_checkpoint_threshold_set")]
  public static extern void kuzu_system_config_checkpoint_threshold_set(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_system_config_checkpoint_threshold_get")]
  public static extern ulong kuzu_system_config_checkpoint_threshold_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_new_kuzu_system_config")]
  public static extern global::System.IntPtr new_kuzu_system_config();

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_delete_kuzu_system_config")]
  public static extern void delete_kuzu_system_config(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_new_kuzu_database")]
  public static extern global::System.IntPtr new_kuzu_database();

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_delete_kuzu_database")]
  public static extern void delete_kuzu_database(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_new_kuzu_connection")]
  public static extern global::System.IntPtr new_kuzu_connection();

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_delete_kuzu_connection")]
  public static extern void delete_kuzu_connection(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_new_kuzu_prepared_statement")]
  public static extern global::System.IntPtr new_kuzu_prepared_statement();

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_delete_kuzu_prepared_statement")]
  public static extern void delete_kuzu_prepared_statement(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_query_result__is_owned_by_cpp_set")]
  public static extern void kuzu_query_result__is_owned_by_cpp_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_query_result__is_owned_by_cpp_get")]
  public static extern bool kuzu_query_result__is_owned_by_cpp_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_new_kuzu_query_result")]
  public static extern global::System.IntPtr new_kuzu_query_result();

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_delete_kuzu_query_result")]
  public static extern void delete_kuzu_query_result(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_flat_tuple__is_owned_by_cpp_set")]
  public static extern void kuzu_flat_tuple__is_owned_by_cpp_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_flat_tuple__is_owned_by_cpp_get")]
  public static extern bool kuzu_flat_tuple__is_owned_by_cpp_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_new_kuzu_flat_tuple")]
  public static extern global::System.IntPtr new_kuzu_flat_tuple();

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_delete_kuzu_flat_tuple")]
  public static extern void delete_kuzu_flat_tuple(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_new_kuzu_logical_type")]
  public static extern global::System.IntPtr new_kuzu_logical_type();

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_delete_kuzu_logical_type")]
  public static extern void delete_kuzu_logical_type(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value__is_owned_by_cpp_set")]
  public static extern void kuzu_value__is_owned_by_cpp_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value__is_owned_by_cpp_get")]
  public static extern bool kuzu_value__is_owned_by_cpp_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_new_kuzu_value")]
  public static extern global::System.IntPtr new_kuzu_value();

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_delete_kuzu_value")]
  public static extern void delete_kuzu_value(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_internal_id_t_table_id_set")]
  public static extern void kuzu_internal_id_t_table_id_set(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_internal_id_t_table_id_get")]
  public static extern ulong kuzu_internal_id_t_table_id_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_internal_id_t_offset_set")]
  public static extern void kuzu_internal_id_t_offset_set(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_internal_id_t_offset_get")]
  public static extern ulong kuzu_internal_id_t_offset_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_new_kuzu_internal_id_t")]
  public static extern global::System.IntPtr new_kuzu_internal_id_t();

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_delete_kuzu_internal_id_t")]
  public static extern void delete_kuzu_internal_id_t(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_date_t_days_set")]
  public static extern void kuzu_date_t_days_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_date_t_days_get")]
  public static extern int kuzu_date_t_days_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_new_kuzu_date_t")]
  public static extern global::System.IntPtr new_kuzu_date_t();

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_delete_kuzu_date_t")]
  public static extern void delete_kuzu_date_t(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_timestamp_ns_t_value_set")]
  public static extern void kuzu_timestamp_ns_t_value_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_timestamp_ns_t_value_get")]
  public static extern long kuzu_timestamp_ns_t_value_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_new_kuzu_timestamp_ns_t")]
  public static extern global::System.IntPtr new_kuzu_timestamp_ns_t();

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_delete_kuzu_timestamp_ns_t")]
  public static extern void delete_kuzu_timestamp_ns_t(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_timestamp_ms_t_value_set")]
  public static extern void kuzu_timestamp_ms_t_value_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_timestamp_ms_t_value_get")]
  public static extern long kuzu_timestamp_ms_t_value_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_new_kuzu_timestamp_ms_t")]
  public static extern global::System.IntPtr new_kuzu_timestamp_ms_t();

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_delete_kuzu_timestamp_ms_t")]
  public static extern void delete_kuzu_timestamp_ms_t(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_timestamp_sec_t_value_set")]
  public static extern void kuzu_timestamp_sec_t_value_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_timestamp_sec_t_value_get")]
  public static extern long kuzu_timestamp_sec_t_value_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_new_kuzu_timestamp_sec_t")]
  public static extern global::System.IntPtr new_kuzu_timestamp_sec_t();

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_delete_kuzu_timestamp_sec_t")]
  public static extern void delete_kuzu_timestamp_sec_t(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_timestamp_tz_t_value_set")]
  public static extern void kuzu_timestamp_tz_t_value_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_timestamp_tz_t_value_get")]
  public static extern long kuzu_timestamp_tz_t_value_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_new_kuzu_timestamp_tz_t")]
  public static extern global::System.IntPtr new_kuzu_timestamp_tz_t();

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_delete_kuzu_timestamp_tz_t")]
  public static extern void delete_kuzu_timestamp_tz_t(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_timestamp_t_value_set")]
  public static extern void kuzu_timestamp_t_value_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_timestamp_t_value_get")]
  public static extern long kuzu_timestamp_t_value_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_new_kuzu_timestamp_t")]
  public static extern global::System.IntPtr new_kuzu_timestamp_t();

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_delete_kuzu_timestamp_t")]
  public static extern void delete_kuzu_timestamp_t(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_interval_t_months_set")]
  public static extern void kuzu_interval_t_months_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_interval_t_months_get")]
  public static extern int kuzu_interval_t_months_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_interval_t_days_set")]
  public static extern void kuzu_interval_t_days_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_interval_t_days_get")]
  public static extern int kuzu_interval_t_days_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_interval_t_micros_set")]
  public static extern void kuzu_interval_t_micros_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_interval_t_micros_get")]
  public static extern long kuzu_interval_t_micros_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_new_kuzu_interval_t")]
  public static extern global::System.IntPtr new_kuzu_interval_t();

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_delete_kuzu_interval_t")]
  public static extern void delete_kuzu_interval_t(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_new_kuzu_query_summary")]
  public static extern global::System.IntPtr new_kuzu_query_summary();

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_delete_kuzu_query_summary")]
  public static extern void delete_kuzu_query_summary(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_int128_t_low_set")]
  public static extern void kuzu_int128_t_low_set(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_int128_t_low_get")]
  public static extern ulong kuzu_int128_t_low_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_int128_t_high_set")]
  public static extern void kuzu_int128_t_high_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_int128_t_high_get")]
  public static extern long kuzu_int128_t_high_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_new_kuzu_int128_t")]
  public static extern global::System.IntPtr new_kuzu_int128_t();

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_delete_kuzu_int128_t")]
  public static extern void delete_kuzu_int128_t(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_database_init")]
  public static extern int kuzu_database_init(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_database_destroy")]
  public static extern void kuzu_database_destroy(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_default_system_config")]
  public static extern global::System.IntPtr kuzu_default_system_config();

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_connection_init")]
  public static extern int kuzu_connection_init(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_connection_destroy")]
  public static extern void kuzu_connection_destroy(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_connection_set_max_num_thread_for_exec")]
  public static extern int kuzu_connection_set_max_num_thread_for_exec(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_connection_get_max_num_thread_for_exec")]
  public static extern int kuzu_connection_get_max_num_thread_for_exec(global::System.Runtime.InteropServices.HandleRef jarg1, out ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_connection_query")]
  public static extern int kuzu_connection_query(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_connection_prepare")]
  public static extern int kuzu_connection_prepare(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_connection_execute")]
  public static extern int kuzu_connection_execute(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_connection_interrupt")]
  public static extern void kuzu_connection_interrupt(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_connection_set_query_timeout")]
  public static extern int kuzu_connection_set_query_timeout(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_prepared_statement_destroy")]
  public static extern void kuzu_prepared_statement_destroy(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_prepared_statement_is_success")]
  public static extern bool kuzu_prepared_statement_is_success(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_prepared_statement_get_error_message")]
  public static extern string kuzu_prepared_statement_get_error_message(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_prepared_statement_bind_bool")]
  public static extern int kuzu_prepared_statement_bind_bool(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_prepared_statement_bind_int64")]
  public static extern int kuzu_prepared_statement_bind_int64(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, long jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_prepared_statement_bind_int32")]
  public static extern int kuzu_prepared_statement_bind_int32(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_prepared_statement_bind_int16")]
  public static extern int kuzu_prepared_statement_bind_int16(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, short jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_prepared_statement_bind_int8")]
  public static extern int kuzu_prepared_statement_bind_int8(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, sbyte jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_prepared_statement_bind_uint64")]
  public static extern int kuzu_prepared_statement_bind_uint64(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, ulong jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_prepared_statement_bind_uint32")]
  public static extern int kuzu_prepared_statement_bind_uint32(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_prepared_statement_bind_uint16")]
  public static extern int kuzu_prepared_statement_bind_uint16(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, ushort jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_prepared_statement_bind_uint8")]
  public static extern int kuzu_prepared_statement_bind_uint8(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, byte jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_prepared_statement_bind_double")]
  public static extern int kuzu_prepared_statement_bind_double(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_prepared_statement_bind_float")]
  public static extern int kuzu_prepared_statement_bind_float(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_prepared_statement_bind_date")]
  public static extern int kuzu_prepared_statement_bind_date(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_prepared_statement_bind_timestamp_ns")]
  public static extern int kuzu_prepared_statement_bind_timestamp_ns(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_prepared_statement_bind_timestamp_sec")]
  public static extern int kuzu_prepared_statement_bind_timestamp_sec(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_prepared_statement_bind_timestamp_tz")]
  public static extern int kuzu_prepared_statement_bind_timestamp_tz(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_prepared_statement_bind_timestamp_ms")]
  public static extern int kuzu_prepared_statement_bind_timestamp_ms(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_prepared_statement_bind_timestamp")]
  public static extern int kuzu_prepared_statement_bind_timestamp(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_prepared_statement_bind_interval")]
  public static extern int kuzu_prepared_statement_bind_interval(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_prepared_statement_bind_string")]
  public static extern int kuzu_prepared_statement_bind_string(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_prepared_statement_bind_value")]
  public static extern int kuzu_prepared_statement_bind_value(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_query_result_destroy")]
  public static extern void kuzu_query_result_destroy(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_query_result_is_success")]
  public static extern bool kuzu_query_result_is_success(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_query_result_get_error_message")]
  public static extern string kuzu_query_result_get_error_message(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_query_result_get_num_columns")]
  public static extern ulong kuzu_query_result_get_num_columns(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_query_result_get_column_name")]
  public static extern int kuzu_query_result_get_column_name(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2, out string jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_query_result_get_column_data_type")]
  public static extern int kuzu_query_result_get_column_data_type(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_query_result_get_num_tuples")]
  public static extern ulong kuzu_query_result_get_num_tuples(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_query_result_get_query_summary")]
  public static extern int kuzu_query_result_get_query_summary(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_query_result_has_next")]
  public static extern bool kuzu_query_result_has_next(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_query_result_get_next")]
  public static extern int kuzu_query_result_get_next(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_query_result_has_next_query_result")]
  public static extern bool kuzu_query_result_has_next_query_result(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_query_result_get_next_query_result")]
  public static extern int kuzu_query_result_get_next_query_result(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_query_result_to_string")]
  public static extern string kuzu_query_result_to_string(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_query_result_reset_iterator")]
  public static extern void kuzu_query_result_reset_iterator(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_flat_tuple_destroy")]
  public static extern void kuzu_flat_tuple_destroy(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_flat_tuple_get_value")]
  public static extern int kuzu_flat_tuple_get_value(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_flat_tuple_to_string")]
  public static extern string kuzu_flat_tuple_to_string(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_data_type_create")]
  public static extern void kuzu_data_type_create(int jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, ulong jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_data_type_clone")]
  public static extern void kuzu_data_type_clone(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_data_type_destroy")]
  public static extern void kuzu_data_type_destroy(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_data_type_equals")]
  public static extern bool kuzu_data_type_equals(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_data_type_get_id")]
  public static extern int kuzu_data_type_get_id(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_data_type_get_num_elements_in_array")]
  public static extern int kuzu_data_type_get_num_elements_in_array(global::System.Runtime.InteropServices.HandleRef jarg1, out ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_null")]
  public static extern global::System.IntPtr kuzu_value_create_null();

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_null_with_data_type")]
  public static extern global::System.IntPtr kuzu_value_create_null_with_data_type(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_is_null")]
  public static extern bool kuzu_value_is_null(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_set_null")]
  public static extern void kuzu_value_set_null(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_default")]
  public static extern global::System.IntPtr kuzu_value_create_default(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_bool")]
  public static extern global::System.IntPtr kuzu_value_create_bool(bool jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_int8")]
  public static extern global::System.IntPtr kuzu_value_create_int8(sbyte jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_int16")]
  public static extern global::System.IntPtr kuzu_value_create_int16(short jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_int32")]
  public static extern global::System.IntPtr kuzu_value_create_int32(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_int64")]
  public static extern global::System.IntPtr kuzu_value_create_int64(long jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_uint8")]
  public static extern global::System.IntPtr kuzu_value_create_uint8(byte jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_uint16")]
  public static extern global::System.IntPtr kuzu_value_create_uint16(ushort jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_uint32")]
  public static extern global::System.IntPtr kuzu_value_create_uint32(uint jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_uint64")]
  public static extern global::System.IntPtr kuzu_value_create_uint64(ulong jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_int128")]
  public static extern global::System.IntPtr kuzu_value_create_int128(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_float")]
  public static extern global::System.IntPtr kuzu_value_create_float(float jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_double")]
  public static extern global::System.IntPtr kuzu_value_create_double(double jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_internal_id")]
  public static extern global::System.IntPtr kuzu_value_create_internal_id(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_date")]
  public static extern global::System.IntPtr kuzu_value_create_date(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_timestamp_ns")]
  public static extern global::System.IntPtr kuzu_value_create_timestamp_ns(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_timestamp_ms")]
  public static extern global::System.IntPtr kuzu_value_create_timestamp_ms(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_timestamp_sec")]
  public static extern global::System.IntPtr kuzu_value_create_timestamp_sec(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_timestamp_tz")]
  public static extern global::System.IntPtr kuzu_value_create_timestamp_tz(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_timestamp")]
  public static extern global::System.IntPtr kuzu_value_create_timestamp(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_interval")]
  public static extern global::System.IntPtr kuzu_value_create_interval(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_string")]
  public static extern global::System.IntPtr kuzu_value_create_string(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_list")]
  public static extern int kuzu_value_create_list(ulong jarg1, kuzu_value[] jarg2, out kuzu_value jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_struct")]
  public static extern int kuzu_value_create_struct(ulong jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, kuzu_value[] jarg3, out kuzu_value jarg4);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_create_map")]
  public static extern int kuzu_value_create_map(ulong jarg1, kuzu_value[] jarg2, kuzu_value[] jarg3, out kuzu_value jarg4);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_clone")]
  public static extern global::System.IntPtr kuzu_value_clone(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_copy")]
  public static extern void kuzu_value_copy(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_destroy")]
  public static extern void kuzu_value_destroy(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_list_size")]
  public static extern int kuzu_value_get_list_size(global::System.Runtime.InteropServices.HandleRef jarg1, out ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_list_element")]
  public static extern int kuzu_value_get_list_element(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_struct_num_fields")]
  public static extern int kuzu_value_get_struct_num_fields(global::System.Runtime.InteropServices.HandleRef jarg1, out ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_struct_field_name")]
  public static extern int kuzu_value_get_struct_field_name(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2, out string jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_struct_field_value")]
  public static extern int kuzu_value_get_struct_field_value(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_map_size")]
  public static extern int kuzu_value_get_map_size(global::System.Runtime.InteropServices.HandleRef jarg1, out ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_map_key")]
  public static extern int kuzu_value_get_map_key(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_map_value")]
  public static extern int kuzu_value_get_map_value(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_recursive_rel_node_list")]
  public static extern int kuzu_value_get_recursive_rel_node_list(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_recursive_rel_rel_list")]
  public static extern int kuzu_value_get_recursive_rel_rel_list(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_data_type")]
  public static extern void kuzu_value_get_data_type(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_bool")]
  public static extern int kuzu_value_get_bool(global::System.Runtime.InteropServices.HandleRef jarg1, out bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_int8")]
  public static extern int kuzu_value_get_int8(global::System.Runtime.InteropServices.HandleRef jarg1, out sbyte jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_int16")]
  public static extern int kuzu_value_get_int16(global::System.Runtime.InteropServices.HandleRef jarg1, out short jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_int32")]
  public static extern int kuzu_value_get_int32(global::System.Runtime.InteropServices.HandleRef jarg1, out int jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_int64")]
  public static extern int kuzu_value_get_int64(global::System.Runtime.InteropServices.HandleRef jarg1, out long jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_uint8")]
  public static extern int kuzu_value_get_uint8(global::System.Runtime.InteropServices.HandleRef jarg1, out byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_uint16")]
  public static extern int kuzu_value_get_uint16(global::System.Runtime.InteropServices.HandleRef jarg1, out ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_uint32")]
  public static extern int kuzu_value_get_uint32(global::System.Runtime.InteropServices.HandleRef jarg1, out uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_uint64")]
  public static extern int kuzu_value_get_uint64(global::System.Runtime.InteropServices.HandleRef jarg1, out ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_int128")]
  public static extern int kuzu_value_get_int128(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_int128_t_from_string")]
  public static extern int kuzu_int128_t_from_string(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_int128_t_to_string")]
  public static extern int kuzu_int128_t_to_string(global::System.Runtime.InteropServices.HandleRef jarg1, out string jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_float")]
  public static extern int kuzu_value_get_float(global::System.Runtime.InteropServices.HandleRef jarg1, out float jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_double")]
  public static extern int kuzu_value_get_double(global::System.Runtime.InteropServices.HandleRef jarg1, out double jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_internal_id")]
  public static extern int kuzu_value_get_internal_id(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_date")]
  public static extern int kuzu_value_get_date(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_timestamp")]
  public static extern int kuzu_value_get_timestamp(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_timestamp_ns")]
  public static extern int kuzu_value_get_timestamp_ns(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_timestamp_ms")]
  public static extern int kuzu_value_get_timestamp_ms(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_timestamp_sec")]
  public static extern int kuzu_value_get_timestamp_sec(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_timestamp_tz")]
  public static extern int kuzu_value_get_timestamp_tz(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_interval")]
  public static extern int kuzu_value_get_interval(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_decimal_as_string")]
  public static extern int kuzu_value_get_decimal_as_string(global::System.Runtime.InteropServices.HandleRef jarg1, out string jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_string")]
  public static extern int kuzu_value_get_string(global::System.Runtime.InteropServices.HandleRef jarg1, out string jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_blob")]
  public static extern int kuzu_value_get_blob(global::System.Runtime.InteropServices.HandleRef jarg1, out byte[] jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_get_uuid")]
  public static extern int kuzu_value_get_uuid(global::System.Runtime.InteropServices.HandleRef jarg1, out string jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_value_to_string")]
  public static extern string kuzu_value_to_string(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_node_val_get_id_val")]
  public static extern int kuzu_node_val_get_id_val(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_node_val_get_label_val")]
  public static extern int kuzu_node_val_get_label_val(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_node_val_get_property_size")]
  public static extern int kuzu_node_val_get_property_size(global::System.Runtime.InteropServices.HandleRef jarg1, out ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_node_val_get_property_name_at")]
  public static extern int kuzu_node_val_get_property_name_at(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2, out string jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_node_val_get_property_value_at")]
  public static extern int kuzu_node_val_get_property_value_at(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_node_val_to_string")]
  public static extern int kuzu_node_val_to_string(global::System.Runtime.InteropServices.HandleRef jarg1, out string jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_rel_val_get_id_val")]
  public static extern int kuzu_rel_val_get_id_val(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_rel_val_get_src_id_val")]
  public static extern int kuzu_rel_val_get_src_id_val(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_rel_val_get_dst_id_val")]
  public static extern int kuzu_rel_val_get_dst_id_val(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_rel_val_get_label_val")]
  public static extern int kuzu_rel_val_get_label_val(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_rel_val_get_property_size")]
  public static extern int kuzu_rel_val_get_property_size(global::System.Runtime.InteropServices.HandleRef jarg1, out ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_rel_val_get_property_name_at")]
  public static extern int kuzu_rel_val_get_property_name_at(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2, out string jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_rel_val_get_property_value_at")]
  public static extern int kuzu_rel_val_get_property_value_at(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_rel_val_to_string")]
  public static extern int kuzu_rel_val_to_string(global::System.Runtime.InteropServices.HandleRef jarg1, out string jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_query_summary_destroy")]
  public static extern void kuzu_query_summary_destroy(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_query_summary_get_compiling_time")]
  public static extern double kuzu_query_summary_get_compiling_time(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_query_summary_get_execution_time")]
  public static extern double kuzu_query_summary_get_execution_time(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_timestamp_ns_to_tm")]
  public static extern int kuzu_timestamp_ns_to_tm(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_timestamp_ms_to_tm")]
  public static extern int kuzu_timestamp_ms_to_tm(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_timestamp_sec_to_tm")]
  public static extern int kuzu_timestamp_sec_to_tm(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_timestamp_tz_to_tm")]
  public static extern int kuzu_timestamp_tz_to_tm(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_timestamp_to_tm")]
  public static extern int kuzu_timestamp_to_tm(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_timestamp_ns_from_tm")]
  public static extern int kuzu_timestamp_ns_from_tm(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_timestamp_ms_from_tm")]
  public static extern int kuzu_timestamp_ms_from_tm(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_timestamp_sec_from_tm")]
  public static extern int kuzu_timestamp_sec_from_tm(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_timestamp_tz_from_tm")]
  public static extern int kuzu_timestamp_tz_from_tm(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_timestamp_from_tm")]
  public static extern int kuzu_timestamp_from_tm(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_date_to_string")]
  public static extern int kuzu_date_to_string(global::System.Runtime.InteropServices.HandleRef jarg1, out string jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_date_from_string")]
  public static extern int kuzu_date_from_string(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_date_to_tm")]
  public static extern int kuzu_date_to_tm(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_date_from_tm")]
  public static extern int kuzu_date_from_tm(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_interval_to_difftime")]
  public static extern void kuzu_interval_to_difftime(global::System.Runtime.InteropServices.HandleRef jarg1, out double jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_interval_from_difftime")]
  public static extern void kuzu_interval_from_difftime(double jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_get_version")]
  public static extern string kuzu_get_version();

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_kuzu_get_storage_version")]
  public static extern ulong kuzu_get_storage_version();

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_tm_tm_sec_set")]
  public static extern void tm_tm_sec_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_tm_tm_sec_get")]
  public static extern int tm_tm_sec_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_tm_tm_min_set")]
  public static extern void tm_tm_min_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_tm_tm_min_get")]
  public static extern int tm_tm_min_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_tm_tm_hour_set")]
  public static extern void tm_tm_hour_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_tm_tm_hour_get")]
  public static extern int tm_tm_hour_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_tm_tm_mday_set")]
  public static extern void tm_tm_mday_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_tm_tm_mday_get")]
  public static extern int tm_tm_mday_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_tm_tm_mon_set")]
  public static extern void tm_tm_mon_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_tm_tm_mon_get")]
  public static extern int tm_tm_mon_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_tm_tm_year_set")]
  public static extern void tm_tm_year_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_tm_tm_year_get")]
  public static extern int tm_tm_year_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_tm_tm_wday_set")]
  public static extern void tm_tm_wday_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_tm_tm_wday_get")]
  public static extern int tm_tm_wday_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_tm_tm_yday_set")]
  public static extern void tm_tm_yday_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_tm_tm_yday_get")]
  public static extern int tm_tm_yday_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_tm_tm_isdst_set")]
  public static extern void tm_tm_isdst_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_tm_tm_isdst_get")]
  public static extern int tm_tm_isdst_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_new_tm")]
  public static extern global::System.IntPtr new_tm();

  [global::System.Runtime.InteropServices.DllImport("kuzunet", EntryPoint="CSharp_delete_tm")]
  public static extern void delete_tm(global::System.Runtime.InteropServices.HandleRef jarg1);
}
