//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class kuzunet {
  public static int kuzu_value_has_internal(kuzu_value value) {
    int ret = kuzunetPINVOKE.kuzu_value_has_internal(kuzu_value.getCPtr(value));
    return ret;
  }

  public static kuzu_state kuzu_database_init(string database_path, kuzu_system_config system_config, kuzu_database out_database) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_database_init(database_path, kuzu_system_config.getCPtr(system_config), kuzu_database.getCPtr(out_database));
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void kuzu_database_destroy(kuzu_database database) {
    kuzunetPINVOKE.kuzu_database_destroy(kuzu_database.getCPtr(database));
  }

  public static kuzu_system_config kuzu_default_system_config() {
    kuzu_system_config ret = new kuzu_system_config(kuzunetPINVOKE.kuzu_default_system_config(), true);
    return ret;
  }

  public static kuzu_state kuzu_connection_init(kuzu_database database, kuzu_connection out_connection) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_connection_init(kuzu_database.getCPtr(database), kuzu_connection.getCPtr(out_connection));
    return ret;
  }

  public static void kuzu_connection_destroy(kuzu_connection connection) {
    kuzunetPINVOKE.kuzu_connection_destroy(kuzu_connection.getCPtr(connection));
  }

  public static kuzu_state kuzu_connection_set_max_num_thread_for_exec(kuzu_connection connection, ulong num_threads) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_connection_set_max_num_thread_for_exec(kuzu_connection.getCPtr(connection), num_threads);
    return ret;
  }

  public static kuzu_state kuzu_connection_get_max_num_thread_for_exec(kuzu_connection connection, out ulong out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_connection_get_max_num_thread_for_exec(kuzu_connection.getCPtr(connection), out out_result);
    return ret;
  }

  public static kuzu_state kuzu_connection_query(kuzu_connection connection, string query, kuzu_query_result out_query_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_connection_query(kuzu_connection.getCPtr(connection), query, kuzu_query_result.getCPtr(out_query_result));
    return ret;
  }

  public static kuzu_state kuzu_connection_prepare(kuzu_connection connection, string query, kuzu_prepared_statement out_prepared_statement) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_connection_prepare(kuzu_connection.getCPtr(connection), query, kuzu_prepared_statement.getCPtr(out_prepared_statement));
    return ret;
  }

  public static kuzu_state kuzu_connection_execute(kuzu_connection connection, kuzu_prepared_statement prepared_statement, kuzu_query_result out_query_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_connection_execute(kuzu_connection.getCPtr(connection), kuzu_prepared_statement.getCPtr(prepared_statement), kuzu_query_result.getCPtr(out_query_result));
    return ret;
  }

  public static void kuzu_connection_interrupt(kuzu_connection connection) {
    kuzunetPINVOKE.kuzu_connection_interrupt(kuzu_connection.getCPtr(connection));
  }

  public static kuzu_state kuzu_connection_set_query_timeout(kuzu_connection connection, ulong timeout_in_ms) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_connection_set_query_timeout(kuzu_connection.getCPtr(connection), timeout_in_ms);
    return ret;
  }

  public static void kuzu_prepared_statement_destroy(kuzu_prepared_statement prepared_statement) {
    kuzunetPINVOKE.kuzu_prepared_statement_destroy(kuzu_prepared_statement.getCPtr(prepared_statement));
  }

  public static bool kuzu_prepared_statement_is_success(kuzu_prepared_statement prepared_statement) {
    bool ret = kuzunetPINVOKE.kuzu_prepared_statement_is_success(kuzu_prepared_statement.getCPtr(prepared_statement));
    return ret;
  }

  public static string kuzu_prepared_statement_get_error_message(kuzu_prepared_statement prepared_statement) {
    string ret = kuzunetPINVOKE.kuzu_prepared_statement_get_error_message(kuzu_prepared_statement.getCPtr(prepared_statement));
    return ret;
  }

  public static kuzu_state kuzu_prepared_statement_bind_bool(kuzu_prepared_statement prepared_statement, string param_name, bool value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_prepared_statement_bind_bool(kuzu_prepared_statement.getCPtr(prepared_statement), param_name, value);
    return ret;
  }

  public static kuzu_state kuzu_prepared_statement_bind_int64(kuzu_prepared_statement prepared_statement, string param_name, long value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_prepared_statement_bind_int64(kuzu_prepared_statement.getCPtr(prepared_statement), param_name, value);
    return ret;
  }

  public static kuzu_state kuzu_prepared_statement_bind_int32(kuzu_prepared_statement prepared_statement, string param_name, int value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_prepared_statement_bind_int32(kuzu_prepared_statement.getCPtr(prepared_statement), param_name, value);
    return ret;
  }

  public static kuzu_state kuzu_prepared_statement_bind_int16(kuzu_prepared_statement prepared_statement, string param_name, short value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_prepared_statement_bind_int16(kuzu_prepared_statement.getCPtr(prepared_statement), param_name, value);
    return ret;
  }

  public static kuzu_state kuzu_prepared_statement_bind_int8(kuzu_prepared_statement prepared_statement, string param_name, sbyte value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_prepared_statement_bind_int8(kuzu_prepared_statement.getCPtr(prepared_statement), param_name, value);
    return ret;
  }

  public static kuzu_state kuzu_prepared_statement_bind_uint64(kuzu_prepared_statement prepared_statement, string param_name, ulong value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_prepared_statement_bind_uint64(kuzu_prepared_statement.getCPtr(prepared_statement), param_name, value);
    return ret;
  }

  public static kuzu_state kuzu_prepared_statement_bind_uint32(kuzu_prepared_statement prepared_statement, string param_name, uint value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_prepared_statement_bind_uint32(kuzu_prepared_statement.getCPtr(prepared_statement), param_name, value);
    return ret;
  }

  public static kuzu_state kuzu_prepared_statement_bind_uint16(kuzu_prepared_statement prepared_statement, string param_name, ushort value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_prepared_statement_bind_uint16(kuzu_prepared_statement.getCPtr(prepared_statement), param_name, value);
    return ret;
  }

  public static kuzu_state kuzu_prepared_statement_bind_uint8(kuzu_prepared_statement prepared_statement, string param_name, byte value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_prepared_statement_bind_uint8(kuzu_prepared_statement.getCPtr(prepared_statement), param_name, value);
    return ret;
  }

  public static kuzu_state kuzu_prepared_statement_bind_double(kuzu_prepared_statement prepared_statement, string param_name, double value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_prepared_statement_bind_double(kuzu_prepared_statement.getCPtr(prepared_statement), param_name, value);
    return ret;
  }

  public static kuzu_state kuzu_prepared_statement_bind_float(kuzu_prepared_statement prepared_statement, string param_name, float value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_prepared_statement_bind_float(kuzu_prepared_statement.getCPtr(prepared_statement), param_name, value);
    return ret;
  }

  public static kuzu_state kuzu_prepared_statement_bind_date(kuzu_prepared_statement prepared_statement, string param_name, kuzu_date_t value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_prepared_statement_bind_date(kuzu_prepared_statement.getCPtr(prepared_statement), param_name, kuzu_date_t.getCPtr(value));
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_state kuzu_prepared_statement_bind_timestamp_ns(kuzu_prepared_statement prepared_statement, string param_name, kuzu_timestamp_ns_t value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_prepared_statement_bind_timestamp_ns(kuzu_prepared_statement.getCPtr(prepared_statement), param_name, kuzu_timestamp_ns_t.getCPtr(value));
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_state kuzu_prepared_statement_bind_timestamp_sec(kuzu_prepared_statement prepared_statement, string param_name, kuzu_timestamp_sec_t value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_prepared_statement_bind_timestamp_sec(kuzu_prepared_statement.getCPtr(prepared_statement), param_name, kuzu_timestamp_sec_t.getCPtr(value));
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_state kuzu_prepared_statement_bind_timestamp_tz(kuzu_prepared_statement prepared_statement, string param_name, kuzu_timestamp_tz_t value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_prepared_statement_bind_timestamp_tz(kuzu_prepared_statement.getCPtr(prepared_statement), param_name, kuzu_timestamp_tz_t.getCPtr(value));
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_state kuzu_prepared_statement_bind_timestamp_ms(kuzu_prepared_statement prepared_statement, string param_name, kuzu_timestamp_ms_t value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_prepared_statement_bind_timestamp_ms(kuzu_prepared_statement.getCPtr(prepared_statement), param_name, kuzu_timestamp_ms_t.getCPtr(value));
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_state kuzu_prepared_statement_bind_timestamp(kuzu_prepared_statement prepared_statement, string param_name, kuzu_timestamp_t value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_prepared_statement_bind_timestamp(kuzu_prepared_statement.getCPtr(prepared_statement), param_name, kuzu_timestamp_t.getCPtr(value));
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_state kuzu_prepared_statement_bind_interval(kuzu_prepared_statement prepared_statement, string param_name, kuzu_interval_t value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_prepared_statement_bind_interval(kuzu_prepared_statement.getCPtr(prepared_statement), param_name, kuzu_interval_t.getCPtr(value));
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_state kuzu_prepared_statement_bind_string(kuzu_prepared_statement prepared_statement, string param_name, string value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_prepared_statement_bind_string(kuzu_prepared_statement.getCPtr(prepared_statement), param_name, value);
    return ret;
  }

  public static kuzu_state kuzu_prepared_statement_bind_value(kuzu_prepared_statement prepared_statement, string param_name, kuzu_value value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_prepared_statement_bind_value(kuzu_prepared_statement.getCPtr(prepared_statement), param_name, kuzu_value.getCPtr(value));
    return ret;
  }

  public static void kuzu_query_result_destroy(kuzu_query_result query_result) {
    kuzunetPINVOKE.kuzu_query_result_destroy(kuzu_query_result.getCPtr(query_result));
  }

  public static bool kuzu_query_result_is_success(kuzu_query_result query_result) {
    bool ret = kuzunetPINVOKE.kuzu_query_result_is_success(kuzu_query_result.getCPtr(query_result));
    return ret;
  }

  public static string kuzu_query_result_get_error_message(kuzu_query_result query_result) {
    string ret = kuzunetPINVOKE.kuzu_query_result_get_error_message(kuzu_query_result.getCPtr(query_result));
    return ret;
  }

  public static ulong kuzu_query_result_get_num_columns(kuzu_query_result query_result) {
    ulong ret = kuzunetPINVOKE.kuzu_query_result_get_num_columns(kuzu_query_result.getCPtr(query_result));
    return ret;
  }

  public static kuzu_state kuzu_query_result_get_column_name(kuzu_query_result query_result, ulong index, out string out_column_name) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_query_result_get_column_name(kuzu_query_result.getCPtr(query_result), index, out out_column_name);
    return ret;
  }

  public static kuzu_state kuzu_query_result_get_column_data_type(kuzu_query_result query_result, ulong index, kuzu_logical_type out_column_data_type) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_query_result_get_column_data_type(kuzu_query_result.getCPtr(query_result), index, kuzu_logical_type.getCPtr(out_column_data_type));
    return ret;
  }

  public static ulong kuzu_query_result_get_num_tuples(kuzu_query_result query_result) {
    ulong ret = kuzunetPINVOKE.kuzu_query_result_get_num_tuples(kuzu_query_result.getCPtr(query_result));
    return ret;
  }

  public static kuzu_state kuzu_query_result_get_query_summary(kuzu_query_result query_result, kuzu_query_summary out_query_summary) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_query_result_get_query_summary(kuzu_query_result.getCPtr(query_result), kuzu_query_summary.getCPtr(out_query_summary));
    return ret;
  }

  public static bool kuzu_query_result_has_next(kuzu_query_result query_result) {
    bool ret = kuzunetPINVOKE.kuzu_query_result_has_next(kuzu_query_result.getCPtr(query_result));
    return ret;
  }

  public static kuzu_state kuzu_query_result_get_next(kuzu_query_result query_result, kuzu_flat_tuple out_flat_tuple) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_query_result_get_next(kuzu_query_result.getCPtr(query_result), kuzu_flat_tuple.getCPtr(out_flat_tuple));
    return ret;
  }

  public static bool kuzu_query_result_has_next_query_result(kuzu_query_result query_result) {
    bool ret = kuzunetPINVOKE.kuzu_query_result_has_next_query_result(kuzu_query_result.getCPtr(query_result));
    return ret;
  }

  public static kuzu_state kuzu_query_result_get_next_query_result(kuzu_query_result query_result, kuzu_query_result out_next_query_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_query_result_get_next_query_result(kuzu_query_result.getCPtr(query_result), kuzu_query_result.getCPtr(out_next_query_result));
    return ret;
  }

  public static string kuzu_query_result_to_string(kuzu_query_result query_result) {
    string ret = kuzunetPINVOKE.kuzu_query_result_to_string(kuzu_query_result.getCPtr(query_result));
    return ret;
  }

  public static void kuzu_query_result_reset_iterator(kuzu_query_result query_result) {
    kuzunetPINVOKE.kuzu_query_result_reset_iterator(kuzu_query_result.getCPtr(query_result));
  }

  public static void kuzu_flat_tuple_destroy(kuzu_flat_tuple flat_tuple) {
    kuzunetPINVOKE.kuzu_flat_tuple_destroy(kuzu_flat_tuple.getCPtr(flat_tuple));
  }

  public static kuzu_state kuzu_flat_tuple_get_value(kuzu_flat_tuple flat_tuple, ulong index, kuzu_value out_value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_flat_tuple_get_value(kuzu_flat_tuple.getCPtr(flat_tuple), index, kuzu_value.getCPtr(out_value));
    return ret;
  }

  public static string kuzu_flat_tuple_to_string(kuzu_flat_tuple flat_tuple) {
    string ret = kuzunetPINVOKE.kuzu_flat_tuple_to_string(kuzu_flat_tuple.getCPtr(flat_tuple));
    return ret;
  }

  public static void kuzu_data_type_create(kuzu_data_type_id id, kuzu_logical_type child_type, ulong num_elements_in_array, kuzu_logical_type out_type) {
    kuzunetPINVOKE.kuzu_data_type_create((int)id, kuzu_logical_type.getCPtr(child_type), num_elements_in_array, kuzu_logical_type.getCPtr(out_type));
  }

  public static void kuzu_data_type_clone(kuzu_logical_type data_type, kuzu_logical_type out_type) {
    kuzunetPINVOKE.kuzu_data_type_clone(kuzu_logical_type.getCPtr(data_type), kuzu_logical_type.getCPtr(out_type));
  }

  public static void kuzu_data_type_destroy(kuzu_logical_type data_type) {
    kuzunetPINVOKE.kuzu_data_type_destroy(kuzu_logical_type.getCPtr(data_type));
  }

  public static bool kuzu_data_type_equals(kuzu_logical_type data_type1, kuzu_logical_type data_type2) {
    bool ret = kuzunetPINVOKE.kuzu_data_type_equals(kuzu_logical_type.getCPtr(data_type1), kuzu_logical_type.getCPtr(data_type2));
    return ret;
  }

  public static kuzu_data_type_id kuzu_data_type_get_id(kuzu_logical_type data_type) {
    kuzu_data_type_id ret = (kuzu_data_type_id)kuzunetPINVOKE.kuzu_data_type_get_id(kuzu_logical_type.getCPtr(data_type));
    return ret;
  }

  public static kuzu_state kuzu_data_type_get_num_elements_in_array(kuzu_logical_type data_type, out ulong out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_data_type_get_num_elements_in_array(kuzu_logical_type.getCPtr(data_type), out out_result);
    return ret;
  }

  public static kuzu_value kuzu_value_create_null() {
    global::System.IntPtr cPtr = kuzunetPINVOKE.kuzu_value_create_null();
    kuzu_value ret = (cPtr == global::System.IntPtr.Zero) ? null : new kuzu_value(cPtr, true);
    return ret;
  }

  public static kuzu_value kuzu_value_create_null_with_data_type(kuzu_logical_type data_type) {
    global::System.IntPtr cPtr = kuzunetPINVOKE.kuzu_value_create_null_with_data_type(kuzu_logical_type.getCPtr(data_type));
    kuzu_value ret = (cPtr == global::System.IntPtr.Zero) ? null : new kuzu_value(cPtr, true);
    return ret;
  }

  public static bool kuzu_value_is_null(kuzu_value value) {
    bool ret = kuzunetPINVOKE.kuzu_value_is_null(kuzu_value.getCPtr(value));
    return ret;
  }

  public static void kuzu_value_set_null(kuzu_value value, bool is_null) {
    kuzunetPINVOKE.kuzu_value_set_null(kuzu_value.getCPtr(value), is_null);
  }

  public static kuzu_value kuzu_value_create_default(kuzu_logical_type data_type) {
    global::System.IntPtr cPtr = kuzunetPINVOKE.kuzu_value_create_default(kuzu_logical_type.getCPtr(data_type));
    kuzu_value ret = (cPtr == global::System.IntPtr.Zero) ? null : new kuzu_value(cPtr, true);
    return ret;
  }

  public static kuzu_value kuzu_value_create_bool(bool val_) {
    global::System.IntPtr cPtr = kuzunetPINVOKE.kuzu_value_create_bool(val_);
    kuzu_value ret = (cPtr == global::System.IntPtr.Zero) ? null : new kuzu_value(cPtr, true);
    return ret;
  }

  public static kuzu_value kuzu_value_create_int8(sbyte val_) {
    global::System.IntPtr cPtr = kuzunetPINVOKE.kuzu_value_create_int8(val_);
    kuzu_value ret = (cPtr == global::System.IntPtr.Zero) ? null : new kuzu_value(cPtr, true);
    return ret;
  }

  public static kuzu_value kuzu_value_create_int16(short val_) {
    global::System.IntPtr cPtr = kuzunetPINVOKE.kuzu_value_create_int16(val_);
    kuzu_value ret = (cPtr == global::System.IntPtr.Zero) ? null : new kuzu_value(cPtr, true);
    return ret;
  }

  public static kuzu_value kuzu_value_create_int32(int val_) {
    global::System.IntPtr cPtr = kuzunetPINVOKE.kuzu_value_create_int32(val_);
    kuzu_value ret = (cPtr == global::System.IntPtr.Zero) ? null : new kuzu_value(cPtr, true);
    return ret;
  }

  public static kuzu_value kuzu_value_create_int64(long val_) {
    global::System.IntPtr cPtr = kuzunetPINVOKE.kuzu_value_create_int64(val_);
    kuzu_value ret = (cPtr == global::System.IntPtr.Zero) ? null : new kuzu_value(cPtr, true);
    return ret;
  }

  public static kuzu_value kuzu_value_create_uint8(byte val_) {
    global::System.IntPtr cPtr = kuzunetPINVOKE.kuzu_value_create_uint8(val_);
    kuzu_value ret = (cPtr == global::System.IntPtr.Zero) ? null : new kuzu_value(cPtr, true);
    return ret;
  }

  public static kuzu_value kuzu_value_create_uint16(ushort val_) {
    global::System.IntPtr cPtr = kuzunetPINVOKE.kuzu_value_create_uint16(val_);
    kuzu_value ret = (cPtr == global::System.IntPtr.Zero) ? null : new kuzu_value(cPtr, true);
    return ret;
  }

  public static kuzu_value kuzu_value_create_uint32(uint val_) {
    global::System.IntPtr cPtr = kuzunetPINVOKE.kuzu_value_create_uint32(val_);
    kuzu_value ret = (cPtr == global::System.IntPtr.Zero) ? null : new kuzu_value(cPtr, true);
    return ret;
  }

  public static kuzu_value kuzu_value_create_uint64(ulong val_) {
    global::System.IntPtr cPtr = kuzunetPINVOKE.kuzu_value_create_uint64(val_);
    kuzu_value ret = (cPtr == global::System.IntPtr.Zero) ? null : new kuzu_value(cPtr, true);
    return ret;
  }

  public static kuzu_value kuzu_value_create_int128(kuzu_int128_t val_) {
    global::System.IntPtr cPtr = kuzunetPINVOKE.kuzu_value_create_int128(kuzu_int128_t.getCPtr(val_));
    kuzu_value ret = (cPtr == global::System.IntPtr.Zero) ? null : new kuzu_value(cPtr, true);
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_value kuzu_value_create_float(float val_) {
    global::System.IntPtr cPtr = kuzunetPINVOKE.kuzu_value_create_float(val_);
    kuzu_value ret = (cPtr == global::System.IntPtr.Zero) ? null : new kuzu_value(cPtr, true);
    return ret;
  }

  public static kuzu_value kuzu_value_create_double(double val_) {
    global::System.IntPtr cPtr = kuzunetPINVOKE.kuzu_value_create_double(val_);
    kuzu_value ret = (cPtr == global::System.IntPtr.Zero) ? null : new kuzu_value(cPtr, true);
    return ret;
  }

  public static kuzu_value kuzu_value_create_internal_id(kuzu_internal_id_t val_) {
    global::System.IntPtr cPtr = kuzunetPINVOKE.kuzu_value_create_internal_id(kuzu_internal_id_t.getCPtr(val_));
    kuzu_value ret = (cPtr == global::System.IntPtr.Zero) ? null : new kuzu_value(cPtr, true);
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_value kuzu_value_create_date(kuzu_date_t val_) {
    global::System.IntPtr cPtr = kuzunetPINVOKE.kuzu_value_create_date(kuzu_date_t.getCPtr(val_));
    kuzu_value ret = (cPtr == global::System.IntPtr.Zero) ? null : new kuzu_value(cPtr, true);
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_value kuzu_value_create_timestamp_ns(kuzu_timestamp_ns_t val_) {
    global::System.IntPtr cPtr = kuzunetPINVOKE.kuzu_value_create_timestamp_ns(kuzu_timestamp_ns_t.getCPtr(val_));
    kuzu_value ret = (cPtr == global::System.IntPtr.Zero) ? null : new kuzu_value(cPtr, true);
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_value kuzu_value_create_timestamp_ms(kuzu_timestamp_ms_t val_) {
    global::System.IntPtr cPtr = kuzunetPINVOKE.kuzu_value_create_timestamp_ms(kuzu_timestamp_ms_t.getCPtr(val_));
    kuzu_value ret = (cPtr == global::System.IntPtr.Zero) ? null : new kuzu_value(cPtr, true);
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_value kuzu_value_create_timestamp_sec(kuzu_timestamp_sec_t val_) {
    global::System.IntPtr cPtr = kuzunetPINVOKE.kuzu_value_create_timestamp_sec(kuzu_timestamp_sec_t.getCPtr(val_));
    kuzu_value ret = (cPtr == global::System.IntPtr.Zero) ? null : new kuzu_value(cPtr, true);
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_value kuzu_value_create_timestamp_tz(kuzu_timestamp_tz_t val_) {
    global::System.IntPtr cPtr = kuzunetPINVOKE.kuzu_value_create_timestamp_tz(kuzu_timestamp_tz_t.getCPtr(val_));
    kuzu_value ret = (cPtr == global::System.IntPtr.Zero) ? null : new kuzu_value(cPtr, true);
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_value kuzu_value_create_timestamp(kuzu_timestamp_t val_) {
    global::System.IntPtr cPtr = kuzunetPINVOKE.kuzu_value_create_timestamp(kuzu_timestamp_t.getCPtr(val_));
    kuzu_value ret = (cPtr == global::System.IntPtr.Zero) ? null : new kuzu_value(cPtr, true);
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_value kuzu_value_create_interval(kuzu_interval_t val_) {
    global::System.IntPtr cPtr = kuzunetPINVOKE.kuzu_value_create_interval(kuzu_interval_t.getCPtr(val_));
    kuzu_value ret = (cPtr == global::System.IntPtr.Zero) ? null : new kuzu_value(cPtr, true);
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_value kuzu_value_create_string(string val_) {
    global::System.IntPtr cPtr = kuzunetPINVOKE.kuzu_value_create_string(val_);
    kuzu_value ret = (cPtr == global::System.IntPtr.Zero) ? null : new kuzu_value(cPtr, true);
    return ret;
  }

  public static kuzu_state kuzu_value_create_list(ulong num_elements, kuzu_value[] elements, out kuzu_value out_value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_create_list(num_elements, elements, out out_value);
    return ret;
  }

  public static kuzu_state kuzu_value_create_struct(ulong num_fields, SWIGTYPE_p_p_char field_names, kuzu_value[] field_values, out kuzu_value out_value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_create_struct(num_fields, SWIGTYPE_p_p_char.getCPtr(field_names), field_values, out out_value);
    return ret;
  }

  public static kuzu_state kuzu_value_create_map(ulong num_fields, kuzu_value[] keys, kuzu_value[] values, out kuzu_value out_value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_create_map(num_fields, keys, values, out out_value);
    return ret;
  }

  public static kuzu_value kuzu_value_clone(kuzu_value value) {
    global::System.IntPtr cPtr = kuzunetPINVOKE.kuzu_value_clone(kuzu_value.getCPtr(value));
    kuzu_value ret = (cPtr == global::System.IntPtr.Zero) ? null : new kuzu_value(cPtr, true);
    return ret;
  }

  public static void kuzu_value_copy(kuzu_value value, kuzu_value other) {
    kuzunetPINVOKE.kuzu_value_copy(kuzu_value.getCPtr(value), kuzu_value.getCPtr(other));
  }

  public static void kuzu_value_destroy(kuzu_value value) {
    kuzunetPINVOKE.kuzu_value_destroy(kuzu_value.getCPtr(value));
  }

  public static kuzu_state kuzu_value_get_list_size(kuzu_value value, out ulong out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_list_size(kuzu_value.getCPtr(value), out out_result);
    return ret;
  }

  public static kuzu_state kuzu_value_get_list_element(kuzu_value value, ulong index, kuzu_value out_value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_list_element(kuzu_value.getCPtr(value), index, kuzu_value.getCPtr(out_value));
    return ret;
  }

  public static kuzu_state kuzu_value_get_struct_num_fields(kuzu_value value, out ulong out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_struct_num_fields(kuzu_value.getCPtr(value), out out_result);
    return ret;
  }

  public static kuzu_state kuzu_value_get_struct_field_name(kuzu_value value, ulong index, out string out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_struct_field_name(kuzu_value.getCPtr(value), index, out out_result);
    return ret;
  }

  public static kuzu_state kuzu_value_get_struct_field_value(kuzu_value value, ulong index, kuzu_value out_value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_struct_field_value(kuzu_value.getCPtr(value), index, kuzu_value.getCPtr(out_value));
    return ret;
  }

  public static kuzu_state kuzu_value_get_map_size(kuzu_value value, out ulong out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_map_size(kuzu_value.getCPtr(value), out out_result);
    return ret;
  }

  public static kuzu_state kuzu_value_get_map_key(kuzu_value value, ulong index, kuzu_value out_key) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_map_key(kuzu_value.getCPtr(value), index, kuzu_value.getCPtr(out_key));
    return ret;
  }

  public static kuzu_state kuzu_value_get_map_value(kuzu_value value, ulong index, kuzu_value out_value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_map_value(kuzu_value.getCPtr(value), index, kuzu_value.getCPtr(out_value));
    return ret;
  }

  public static kuzu_state kuzu_value_get_recursive_rel_node_list(kuzu_value value, kuzu_value out_value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_recursive_rel_node_list(kuzu_value.getCPtr(value), kuzu_value.getCPtr(out_value));
    return ret;
  }

  public static kuzu_state kuzu_value_get_recursive_rel_rel_list(kuzu_value value, kuzu_value out_value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_recursive_rel_rel_list(kuzu_value.getCPtr(value), kuzu_value.getCPtr(out_value));
    return ret;
  }

  public static void kuzu_value_get_data_type(kuzu_value value, kuzu_logical_type out_type) {
    kuzunetPINVOKE.kuzu_value_get_data_type(kuzu_value.getCPtr(value), kuzu_logical_type.getCPtr(out_type));
  }

  public static kuzu_state kuzu_value_get_bool(kuzu_value value, out bool out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_bool(kuzu_value.getCPtr(value), out out_result);
    return ret;
  }

  public static kuzu_state kuzu_value_get_int8(kuzu_value value, out sbyte out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_int8(kuzu_value.getCPtr(value), out out_result);
    return ret;
  }

  public static kuzu_state kuzu_value_get_int16(kuzu_value value, out short out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_int16(kuzu_value.getCPtr(value), out out_result);
    return ret;
  }

  public static kuzu_state kuzu_value_get_int32(kuzu_value value, out int out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_int32(kuzu_value.getCPtr(value), out out_result);
    return ret;
  }

  public static kuzu_state kuzu_value_get_int64(kuzu_value value, out long out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_int64(kuzu_value.getCPtr(value), out out_result);
    return ret;
  }

  public static kuzu_state kuzu_value_get_uint8(kuzu_value value, out byte out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_uint8(kuzu_value.getCPtr(value), out out_result);
    return ret;
  }

  public static kuzu_state kuzu_value_get_uint16(kuzu_value value, out ushort out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_uint16(kuzu_value.getCPtr(value), out out_result);
    return ret;
  }

  public static kuzu_state kuzu_value_get_uint32(kuzu_value value, out uint out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_uint32(kuzu_value.getCPtr(value), out out_result);
    return ret;
  }

  public static kuzu_state kuzu_value_get_uint64(kuzu_value value, out ulong out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_uint64(kuzu_value.getCPtr(value), out out_result);
    return ret;
  }

  public static kuzu_state kuzu_value_get_int128(kuzu_value value, kuzu_int128_t out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_int128(kuzu_value.getCPtr(value), kuzu_int128_t.getCPtr(out_result));
    return ret;
  }

  public static kuzu_state kuzu_int128_t_from_string(string str, kuzu_int128_t out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_int128_t_from_string(str, kuzu_int128_t.getCPtr(out_result));
    return ret;
  }

  public static kuzu_state kuzu_int128_t_to_string(kuzu_int128_t val, out string out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_int128_t_to_string(kuzu_int128_t.getCPtr(val), out out_result);
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_state kuzu_value_get_float(kuzu_value value, out float out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_float(kuzu_value.getCPtr(value), out out_result);
    return ret;
  }

  public static kuzu_state kuzu_value_get_double(kuzu_value value, out double out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_double(kuzu_value.getCPtr(value), out out_result);
    return ret;
  }

  public static kuzu_state kuzu_value_get_internal_id(kuzu_value value, kuzu_internal_id_t out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_internal_id(kuzu_value.getCPtr(value), kuzu_internal_id_t.getCPtr(out_result));
    return ret;
  }

  public static kuzu_state kuzu_value_get_date(kuzu_value value, kuzu_date_t out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_date(kuzu_value.getCPtr(value), kuzu_date_t.getCPtr(out_result));
    return ret;
  }

  public static kuzu_state kuzu_value_get_timestamp(kuzu_value value, kuzu_timestamp_t out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_timestamp(kuzu_value.getCPtr(value), kuzu_timestamp_t.getCPtr(out_result));
    return ret;
  }

  public static kuzu_state kuzu_value_get_timestamp_ns(kuzu_value value, kuzu_timestamp_ns_t out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_timestamp_ns(kuzu_value.getCPtr(value), kuzu_timestamp_ns_t.getCPtr(out_result));
    return ret;
  }

  public static kuzu_state kuzu_value_get_timestamp_ms(kuzu_value value, kuzu_timestamp_ms_t out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_timestamp_ms(kuzu_value.getCPtr(value), kuzu_timestamp_ms_t.getCPtr(out_result));
    return ret;
  }

  public static kuzu_state kuzu_value_get_timestamp_sec(kuzu_value value, kuzu_timestamp_sec_t out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_timestamp_sec(kuzu_value.getCPtr(value), kuzu_timestamp_sec_t.getCPtr(out_result));
    return ret;
  }

  public static kuzu_state kuzu_value_get_timestamp_tz(kuzu_value value, kuzu_timestamp_tz_t out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_timestamp_tz(kuzu_value.getCPtr(value), kuzu_timestamp_tz_t.getCPtr(out_result));
    return ret;
  }

  public static kuzu_state kuzu_value_get_interval(kuzu_value value, kuzu_interval_t out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_interval(kuzu_value.getCPtr(value), kuzu_interval_t.getCPtr(out_result));
    return ret;
  }

  public static kuzu_state kuzu_value_get_decimal_as_string(kuzu_value value, out string out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_decimal_as_string(kuzu_value.getCPtr(value), out out_result);
    return ret;
  }

  public static kuzu_state kuzu_value_get_string(kuzu_value value, out string out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_string(kuzu_value.getCPtr(value), out out_result);
    return ret;
  }

  public static kuzu_state kuzu_value_get_blob(kuzu_value value, out byte[] out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_blob(kuzu_value.getCPtr(value), out out_result);
    return ret;
  }

  public static kuzu_state kuzu_value_get_uuid(kuzu_value value, out string out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_value_get_uuid(kuzu_value.getCPtr(value), out out_result);
    return ret;
  }

  public static string kuzu_value_to_string(kuzu_value value) {
    string ret = kuzunetPINVOKE.kuzu_value_to_string(kuzu_value.getCPtr(value));
    return ret;
  }

  public static kuzu_state kuzu_node_val_get_id_val(kuzu_value node_val, kuzu_value out_value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_node_val_get_id_val(kuzu_value.getCPtr(node_val), kuzu_value.getCPtr(out_value));
    return ret;
  }

  public static kuzu_state kuzu_node_val_get_label_val(kuzu_value node_val, kuzu_value out_value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_node_val_get_label_val(kuzu_value.getCPtr(node_val), kuzu_value.getCPtr(out_value));
    return ret;
  }

  public static kuzu_state kuzu_node_val_get_property_size(kuzu_value node_val, out ulong out_value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_node_val_get_property_size(kuzu_value.getCPtr(node_val), out out_value);
    return ret;
  }

  public static kuzu_state kuzu_node_val_get_property_name_at(kuzu_value node_val, ulong index, out string out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_node_val_get_property_name_at(kuzu_value.getCPtr(node_val), index, out out_result);
    return ret;
  }

  public static kuzu_state kuzu_node_val_get_property_value_at(kuzu_value node_val, ulong index, kuzu_value out_value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_node_val_get_property_value_at(kuzu_value.getCPtr(node_val), index, kuzu_value.getCPtr(out_value));
    return ret;
  }

  public static kuzu_state kuzu_node_val_to_string(kuzu_value node_val, out string out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_node_val_to_string(kuzu_value.getCPtr(node_val), out out_result);
    return ret;
  }

  public static kuzu_state kuzu_rel_val_get_id_val(kuzu_value rel_val, kuzu_value out_value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_rel_val_get_id_val(kuzu_value.getCPtr(rel_val), kuzu_value.getCPtr(out_value));
    return ret;
  }

  public static kuzu_state kuzu_rel_val_get_src_id_val(kuzu_value rel_val, kuzu_value out_value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_rel_val_get_src_id_val(kuzu_value.getCPtr(rel_val), kuzu_value.getCPtr(out_value));
    return ret;
  }

  public static kuzu_state kuzu_rel_val_get_dst_id_val(kuzu_value rel_val, kuzu_value out_value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_rel_val_get_dst_id_val(kuzu_value.getCPtr(rel_val), kuzu_value.getCPtr(out_value));
    return ret;
  }

  public static kuzu_state kuzu_rel_val_get_label_val(kuzu_value rel_val, kuzu_value out_value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_rel_val_get_label_val(kuzu_value.getCPtr(rel_val), kuzu_value.getCPtr(out_value));
    return ret;
  }

  public static kuzu_state kuzu_rel_val_get_property_size(kuzu_value rel_val, out ulong out_value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_rel_val_get_property_size(kuzu_value.getCPtr(rel_val), out out_value);
    return ret;
  }

  public static kuzu_state kuzu_rel_val_get_property_name_at(kuzu_value rel_val, ulong index, out string out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_rel_val_get_property_name_at(kuzu_value.getCPtr(rel_val), index, out out_result);
    return ret;
  }

  public static kuzu_state kuzu_rel_val_get_property_value_at(kuzu_value rel_val, ulong index, kuzu_value out_value) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_rel_val_get_property_value_at(kuzu_value.getCPtr(rel_val), index, kuzu_value.getCPtr(out_value));
    return ret;
  }

  public static kuzu_state kuzu_rel_val_to_string(kuzu_value rel_val, out string out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_rel_val_to_string(kuzu_value.getCPtr(rel_val), out out_result);
    return ret;
  }

  public static void kuzu_query_summary_destroy(kuzu_query_summary query_summary) {
    kuzunetPINVOKE.kuzu_query_summary_destroy(kuzu_query_summary.getCPtr(query_summary));
  }

  public static double kuzu_query_summary_get_compiling_time(kuzu_query_summary query_summary) {
    double ret = kuzunetPINVOKE.kuzu_query_summary_get_compiling_time(kuzu_query_summary.getCPtr(query_summary));
    return ret;
  }

  public static double kuzu_query_summary_get_execution_time(kuzu_query_summary query_summary) {
    double ret = kuzunetPINVOKE.kuzu_query_summary_get_execution_time(kuzu_query_summary.getCPtr(query_summary));
    return ret;
  }

  public static kuzu_state kuzu_timestamp_ns_to_tm(kuzu_timestamp_ns_t timestamp, tm out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_timestamp_ns_to_tm(kuzu_timestamp_ns_t.getCPtr(timestamp), tm.getCPtr(out_result));
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_state kuzu_timestamp_ms_to_tm(kuzu_timestamp_ms_t timestamp, tm out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_timestamp_ms_to_tm(kuzu_timestamp_ms_t.getCPtr(timestamp), tm.getCPtr(out_result));
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_state kuzu_timestamp_sec_to_tm(kuzu_timestamp_sec_t timestamp, tm out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_timestamp_sec_to_tm(kuzu_timestamp_sec_t.getCPtr(timestamp), tm.getCPtr(out_result));
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_state kuzu_timestamp_tz_to_tm(kuzu_timestamp_tz_t timestamp, tm out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_timestamp_tz_to_tm(kuzu_timestamp_tz_t.getCPtr(timestamp), tm.getCPtr(out_result));
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_state kuzu_timestamp_to_tm(kuzu_timestamp_t timestamp, tm out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_timestamp_to_tm(kuzu_timestamp_t.getCPtr(timestamp), tm.getCPtr(out_result));
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_state kuzu_timestamp_ns_from_tm(tm tm, kuzu_timestamp_ns_t out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_timestamp_ns_from_tm(tm.getCPtr(tm), kuzu_timestamp_ns_t.getCPtr(out_result));
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_state kuzu_timestamp_ms_from_tm(tm tm, kuzu_timestamp_ms_t out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_timestamp_ms_from_tm(tm.getCPtr(tm), kuzu_timestamp_ms_t.getCPtr(out_result));
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_state kuzu_timestamp_sec_from_tm(tm tm, kuzu_timestamp_sec_t out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_timestamp_sec_from_tm(tm.getCPtr(tm), kuzu_timestamp_sec_t.getCPtr(out_result));
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_state kuzu_timestamp_tz_from_tm(tm tm, kuzu_timestamp_tz_t out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_timestamp_tz_from_tm(tm.getCPtr(tm), kuzu_timestamp_tz_t.getCPtr(out_result));
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_state kuzu_timestamp_from_tm(tm tm, kuzu_timestamp_t out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_timestamp_from_tm(tm.getCPtr(tm), kuzu_timestamp_t.getCPtr(out_result));
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_state kuzu_date_to_string(kuzu_date_t date, out string out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_date_to_string(kuzu_date_t.getCPtr(date), out out_result);
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_state kuzu_date_from_string(string str, kuzu_date_t out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_date_from_string(str, kuzu_date_t.getCPtr(out_result));
    return ret;
  }

  public static kuzu_state kuzu_date_to_tm(kuzu_date_t date, tm out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_date_to_tm(kuzu_date_t.getCPtr(date), tm.getCPtr(out_result));
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static kuzu_state kuzu_date_from_tm(tm tm, kuzu_date_t out_result) {
    kuzu_state ret = (kuzu_state)kuzunetPINVOKE.kuzu_date_from_tm(tm.getCPtr(tm), kuzu_date_t.getCPtr(out_result));
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void kuzu_interval_to_difftime(kuzu_interval_t interval, out double out_result) {
    kuzunetPINVOKE.kuzu_interval_to_difftime(kuzu_interval_t.getCPtr(interval), out out_result);
    if (kuzunetPINVOKE.SWIGPendingException.Pending) throw kuzunetPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void kuzu_interval_from_difftime(double difftime, kuzu_interval_t out_result) {
    kuzunetPINVOKE.kuzu_interval_from_difftime(difftime, kuzu_interval_t.getCPtr(out_result));
  }

  public static string kuzu_get_version() {
    string ret = kuzunetPINVOKE.kuzu_get_version();
    return ret;
  }

  public static ulong kuzu_get_storage_version() {
    ulong ret = kuzunetPINVOKE.kuzu_get_storage_version();
    return ret;
  }

}
