//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class tm : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal tm(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(tm obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(tm obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~tm() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          kuzunetPINVOKE.delete_tm(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int tm_sec {
    set {
      kuzunetPINVOKE.tm_tm_sec_set(swigCPtr, value);
    } 
    get {
      int ret = kuzunetPINVOKE.tm_tm_sec_get(swigCPtr);
      return ret;
    } 
  }

  public int tm_min {
    set {
      kuzunetPINVOKE.tm_tm_min_set(swigCPtr, value);
    } 
    get {
      int ret = kuzunetPINVOKE.tm_tm_min_get(swigCPtr);
      return ret;
    } 
  }

  public int tm_hour {
    set {
      kuzunetPINVOKE.tm_tm_hour_set(swigCPtr, value);
    } 
    get {
      int ret = kuzunetPINVOKE.tm_tm_hour_get(swigCPtr);
      return ret;
    } 
  }

  public int tm_mday {
    set {
      kuzunetPINVOKE.tm_tm_mday_set(swigCPtr, value);
    } 
    get {
      int ret = kuzunetPINVOKE.tm_tm_mday_get(swigCPtr);
      return ret;
    } 
  }

  public int tm_mon {
    set {
      kuzunetPINVOKE.tm_tm_mon_set(swigCPtr, value);
    } 
    get {
      int ret = kuzunetPINVOKE.tm_tm_mon_get(swigCPtr);
      return ret;
    } 
  }

  public int tm_year {
    set {
      kuzunetPINVOKE.tm_tm_year_set(swigCPtr, value);
    } 
    get {
      int ret = kuzunetPINVOKE.tm_tm_year_get(swigCPtr);
      return ret;
    } 
  }

  public int tm_wday {
    set {
      kuzunetPINVOKE.tm_tm_wday_set(swigCPtr, value);
    } 
    get {
      int ret = kuzunetPINVOKE.tm_tm_wday_get(swigCPtr);
      return ret;
    } 
  }

  public int tm_yday {
    set {
      kuzunetPINVOKE.tm_tm_yday_set(swigCPtr, value);
    } 
    get {
      int ret = kuzunetPINVOKE.tm_tm_yday_get(swigCPtr);
      return ret;
    } 
  }

  public int tm_isdst {
    set {
      kuzunetPINVOKE.tm_tm_isdst_set(swigCPtr, value);
    } 
    get {
      int ret = kuzunetPINVOKE.tm_tm_isdst_get(swigCPtr);
      return ret;
    } 
  }

  public tm() : this(kuzunetPINVOKE.new_tm(), true) {
  }

}
